name: Android CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Android Build
        uses: vgaidarji/android-github-actions-build@v1.0.1

- name: "Build Android project"
  uses: vgaidarji/android-github-actions-build@v1.0.1
  with:
    args: "./gradlew assembleDebug"
