- name: Check out
  uses: actions/checkout@v4
- name: Set up JDK
  uses: actions/setup-java@v4
  with:
    distribution: 'zulu'
    java-version: 11
- name: Build with Gradle
  run: ./gradlew assembleRelease
- name: Get apk path
  id: apk-path
  run: echo "path=$(find . -regex '^.*/build/outputs/apk/.*\.apk$' -type f | head -1)" >> $GITHUB_OUTPUT
- name: Get apk info
  id: apk-info
  uses: hkusu/apk-info-action@v1.0.3
  with:
    apk-path: ${{ steps.apk-path.outputs.path }}
- name: Show apk info
  run: |
    echo '${{ steps.apk-info.outputs.application-name }}'
    echo '${{ steps.apk-info.outputs.application-id }}'
    echo '${{ steps.apk-info.outputs.version-code }}'
    echo '${{ steps.apk-info.outputs.version-name }}'
    echo '${{ steps.apk-info.outputs.min-sdk-version }}'
    echo '${{ steps.apk-info.outputs.target-sdk-version }}'
    echo '${{ steps.apk-info.outputs.compile-sdk-version }}'
    echo '${{ steps.apk-info.outputs.uses-permissions }}'
    echo '${{ steps.apk-info.outputs.debuggable }}'
    echo '${{ steps.apk-info.outputs.allow-backup }}'
    echo '${{ steps.apk-info.outputs.supports-rtl }}'
    echo '${{ steps.apk-info.outputs.file-size }}'
    echo '${{ steps.apk-info.outputs.readable-file-size }}'

- uses: hkusu/apk-info-action@v1.0.3
  id: apk-info
  with:
    apk-path: 'Mons_Awaken_2.0_Apkpure.apk'
- name: Show result
  if: always()
  run: echo '${{ steps.apk-info.outputs.result }}' # success or failure
